spring:
  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。

  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        ## all-server 服务
        - id: all-server-api # 路由的编号
          uri: grayLb://all-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/**
          filters:
            - RewritePath=/admin-api/**/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        ## all-server 服务
        - id: all-server # 路由的编号
          uri: grayLb://all-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/**
          filters:
            - RewritePath=/app-api/**/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
      x-forwarded:
        prefix-enabled: false # 避免 Swagger 重复带上额外的 /admin-api/system 前缀
